# container file to build frr from source to test code changes

FROM debian:12

# update the image first
RUN apt-get update

# install package dependancies for frr on debian 12
RUN apt-get install git autoconf automake libtool make \
libprotobuf-c-dev protobuf-c-compiler build-essential \
python3-dev python3-pytest python3-sphinx libjson-c-dev \
libelf-dev libreadline-dev cmake libcap-dev bison flex \
pkg-config texinfo gdb libgrpc-dev python3-grpc-tools -y

# install ping
RUN apt install iputils-ping -y

# install libyang dependancies
RUN apt-get install libpcre2-dev -y

# build and install libyang
WORKDIR /tmp/libyang/
RUN git clone https://github.com/CESNET/libyang.git /tmp/libyang
RUN git checkout v2.1.128
RUN mkdir build
WORKDIR /tmp/libyang/build
RUN cmake --install-prefix /usr -D CMAKE_BUILD_TYPE:String="Release" ..
RUN make
RUN make install

# add frr users and groups
RUN addgroup --system --gid 92 frr
RUN addgroup --system --gid 85 frrvty
RUN adduser --system --ingroup frr --home /var/opt/frr/ --gecos "FRR suite" --shell /bin/false frr
RUN usermod -a -G frrvty frr

# download and build frr
RUN rm -rf /tmp/frr
RUN date >> /dev/null && git clone https://github.com/adamfitz/frr.git /tmp/frr
WORKDIR /tmp/frr
RUN git reset --hard origin/ping_repeat
RUN git fetch --all
RUN git checkout ping_repeat
RUN git pull 
RUN ./bootstrap.sh
RUN ./configure \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --sbindir=/usr/lib/frr \
    --enable-multipath=64 \
    --enable-user=frr \
    --enable-group=frr \
    --enable-vty-group=frrvty \
    --enable-configfile-mask=0640 \
    --enable-logfile-mask=0640 \
    --enable-fpm \
    --with-pkg-git-version \
    --with-pkg-extra-version=-frrDockerfileBuild
RUN make
RUN make check
RUN make install

# workaround for libfrr.so.0 shared object error
RUN echo "include /usr/local/lib" >> /etc/ld.so.conf
RUN ldconfig

# create /etc/frr dir
RUN mkdir /etc/frr

# create frr config files
RUN install -m 640 -o frr -g frr /dev/null /etc/frr/frr.conf
WORKDIR /tmp/frr
RUN install -m 640 -o frr -g frr tools/etc/frr/daemons /etc/frr/daemons

# enable all daemons
RUN sed -i -e 's/zebra=no/zebra=yes/g' /etc/frr/daemons
RUN sed -i -e 's/bgpd=no/bgpd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/ospfd=no/ospfd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/ospf6d=no/ospf6d=yes/g' /etc/frr/daemons
RUN sed -i -e 's/ripd=no/ripd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/ripngd=no/ripngd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/isisd=no/isisd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/ldpd=no/ldpd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/pimd=no/pimd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/nhrpd=no/nhrpd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/eigrpd=no/eigrpd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/babeld=no/babeld=yess/g' /etc/frr/daemons
RUN sed -i -e 's/sharpd=no/sharpd=yes/g' /etc/frr/daemons
RUN sed -i -e 's/pbrd=no/pbrd=yes/g' /etc/frr/daemons

# create vtysh config file
RUN touch /etc/frr/vtysh.conf

# enable IP forwarding
#RUN echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
# ipv4 forwarding is already enabled, check with the below
#RUN sysctl net.ipv4.ip_forward

# start FRR when user logs in (for testing otherwise vtysh wont start)
RUN echo "/usr/lib/frr/zebra -d -f /etc/frr/zebra.conf" >> ~/.bashrc
RUN echo "/usr/lib/frr/bgpd -d -f /etc/frr/bgpd.conf" >> ~/.bashrc

